# Generated by Django 5.1.3 on 2024-11-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_userprofile_invite_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="activated_invite_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
